{"name": "test_coupon_des", "status": "broken", "statusDetails": {"message": "FileNotFoundError: [Errno 2] No such file or directory: '..\\\\log\\\\站群.txt'", "trace": "self = <test_case.test_found.Testfound object at 0x0000028694305730>\n\n    def test_coupon_des(self):\n        log_file_path = r'..\\log\\站群.txt'\n        store_detail = TemuFound()\n        c1 = store_detail.first_des()\n        c2 = store_detail.sec_des()\n        print(c1)\n        print(c2)\n        try:\n            print(\"*-*\" * 28,\"【判断coupon的描述】\",\"*-*\" * 28)\n            assert c1 == des1 and c2 == des2, f\"WA0262-found 前两张coupon的描述内容错误\"    #  coupon描述断言\n    \n            get_deal_found = store_detail.link_ele()\n            print(get_deal_found)\n>           assert get_deal_found == link_found, f\"WA0262-found get deal的affi-Link链接错误\"   #  get deal的affi-Link断言\nE           AssertionError: WA0262-found get deal的affi-Link链接错误\nE           assert '' == 'https://temu...m/u2rh64mil0s'\nE             \nE             - https://temu.to/m/u2rh64mil0s\n\ntest_case\\test_found.py:21: AssertionError\n\nDuring handling of the above exception, another exception occurred:\n\nself = <test_case.test_found.Testfound object at 0x0000028694305730>\n\n    def test_coupon_des(self):\n        log_file_path = r'..\\log\\站群.txt'\n        store_detail = TemuFound()\n        c1 = store_detail.first_des()\n        c2 = store_detail.sec_des()\n        print(c1)\n        print(c2)\n        try:\n            print(\"*-*\" * 28,\"【判断coupon的描述】\",\"*-*\" * 28)\n            assert c1 == des1 and c2 == des2, f\"WA0262-found 前两张coupon的描述内容错误\"    #  coupon描述断言\n    \n            get_deal_found = store_detail.link_ele()\n            print(get_deal_found)\n            assert get_deal_found == link_found, f\"WA0262-found get deal的affi-Link链接错误\"   #  get deal的affi-Link断言\n    \n            affi_code1 = store_detail.first_code()\n            print(affi_code1)\n            assert affi_code1 == code_found, f\"WA0262-found的第一个affi-Code错误\"\n    \n            store_detail.copy_code()\n            affi_code1_link = store_detail.code_link()\n            assert affi_code1_link == link_found, f\"WA0262-found的第一个affi-link错误\"\n    \n            affi_code2 = store_detail.sec_code()\n            print(affi_code2)\n            assert affi_code2 == code_found, f\"WA0262-found的第二个affi-Code错误\"\n    \n            store_detail.copy_code()\n            affi_code2_link = store_detail.code_link()\n            assert affi_code2_link == link_found, f\"WA0262-found的第二个affi-link错误\"\n    \n        except AssertionError as AE:\n            error_log = str(AE)\n>           log_error(log_file_path, error_log)\n\ntest_case\\test_found.py:41: \n_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _\n\nfile = '..\\\\log\\\\站群.txt', info = \"WA0262-found get deal的affi-Link链接错误\\nassert '' == 'https://temu...m/u2rh64mil0s'\\n  \\n  - https://temu.to/m/u2rh64mil0s\"\n\n    def log_error(file,info):\n        current_time = time.strftime('%Y-%m-%d %H:%M:%S')\n        error_info = current_time+ ' ' + info   #字符串拼接\n        #生成一个txt文件\n>       with open(file, 'a', encoding= 'utf-8') as f:\nE       FileNotFoundError: [Errno 2] No such file or directory: '..\\\\log\\\\站群.txt'\n\nlog\\get_log.py:14: FileNotFoundError"}, "start": 1712667715813, "stop": 1712667720213, "uuid": "73ce0c71-a410-40a9-8715-afbd02eb3bf0", "historyId": "a9793d0fd21e7697a86725842f90e731", "testCaseId": "a9793d0fd21e7697a86725842f90e731", "fullName": "test_case.test_found.Testfound#test_coupon_des", "labels": [{"name": "parentSuite", "value": "test_case"}, {"name": "suite", "value": "test_found"}, {"name": "subSuite", "value": "Testfound"}, {"name": "host", "value": "DESKTOP-LPVFBLF"}, {"name": "thread", "value": "9284-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "test_case.test_found"}]}